/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as ShareShareIdIndexRouteImport } from './routes/share/$shareId/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as TeamsTeamIdSettingsRouteImport } from './routes/teams/$teamId/settings'
import { Route as TeamsTeamIdDashboardRouteImport } from './routes/teams/$teamId/dashboard'
import { Route as ProjectsProjectIdRecentlyDeletedRouteImport } from './routes/projects/$projectId/recently-deleted'
import { Route as ProjectsProjectIdAgentsmdRouteImport } from './routes/projects/$projectId/agentsmd'
import { Route as ProjectsProjectIdSharesIndexRouteImport } from './routes/projects/$projectId/shares/index'
import { Route as ProjectsProjectIdCollectionsIndexRouteImport } from './routes/projects/$projectId/collections/index'
import { Route as ShareShareIdFoldersFolderIdRouteImport } from './routes/share/$shareId/folders/$folderId'
import { Route as ShareShareIdFilesFileIdRouteImport } from './routes/share/$shareId/files/$fileId'
import { Route as ProjectsProjectIdSharesShareIdRouteImport } from './routes/projects/$projectId/shares/$shareId'
import { Route as ProjectsProjectIdFoldersFolderIdRouteImport } from './routes/projects/$projectId/folders/$folderId'
import { Route as ProjectsProjectIdFilesFileIdRouteImport } from './routes/projects/$projectId/files/$fileId'
import { Route as ProjectsProjectIdCollectionsCollectionIdRouteImport } from './routes/projects/$projectId/collections/$collectionId'
import { Route as ProjectsProjectIdFoldersFolderIdAgentsmdRouteImport } from './routes/projects/$projectId/folders/$folderId_.agentsmd'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams/$teamId/index.lazy').then((d) => d.Route))
const ShareShareIdIndexRoute = ShareShareIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareShareIdRoute,
} as any).lazy(() => import('./routes/share/$shareId/index.lazy').then((d) => d.Route))
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects/$projectId/index.lazy').then((d) => d.Route))
const TeamsTeamIdSettingsRoute = TeamsTeamIdSettingsRouteImport.update({
  id: '/teams/$teamId/settings',
  path: '/teams/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams/$teamId/settings.lazy').then((d) => d.Route))
const TeamsTeamIdDashboardRoute = TeamsTeamIdDashboardRouteImport.update({
  id: '/teams/$teamId/dashboard',
  path: '/teams/$teamId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams/$teamId/dashboard.lazy').then((d) => d.Route))
const ProjectsProjectIdRecentlyDeletedRoute = ProjectsProjectIdRecentlyDeletedRouteImport.update({
  id: '/projects/$projectId/recently-deleted',
  path: '/projects/$projectId/recently-deleted',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$projectId/recently-deleted.lazy').then((d) => d.Route),
)
const ProjectsProjectIdAgentsmdRoute = ProjectsProjectIdAgentsmdRouteImport.update({
  id: '/projects/$projectId/agentsmd',
  path: '/projects/$projectId/agentsmd',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects/$projectId/agentsmd.lazy').then((d) => d.Route))
const ProjectsProjectIdSharesIndexRoute = ProjectsProjectIdSharesIndexRouteImport.update({
  id: '/projects/$projectId/shares/',
  path: '/projects/$projectId/shares/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects/$projectId/shares/index.lazy').then((d) => d.Route))
const ProjectsProjectIdCollectionsIndexRoute = ProjectsProjectIdCollectionsIndexRouteImport.update({
  id: '/projects/$projectId/collections/',
  path: '/projects/$projectId/collections/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$projectId/collections/index.lazy').then((d) => d.Route),
)
const ShareShareIdFoldersFolderIdRoute = ShareShareIdFoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => ShareShareIdRoute,
} as any).lazy(() => import('./routes/share/$shareId/folders/$folderId.lazy').then((d) => d.Route))
const ShareShareIdFilesFileIdRoute = ShareShareIdFilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => ShareShareIdRoute,
} as any).lazy(() => import('./routes/share/$shareId/files/$fileId.lazy').then((d) => d.Route))
const ProjectsProjectIdSharesShareIdRoute = ProjectsProjectIdSharesShareIdRouteImport.update({
  id: '/projects/$projectId/shares/$shareId',
  path: '/projects/$projectId/shares/$shareId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$projectId/shares/$shareId.lazy').then((d) => d.Route),
)
const ProjectsProjectIdFoldersFolderIdRoute = ProjectsProjectIdFoldersFolderIdRouteImport.update({
  id: '/projects/$projectId/folders/$folderId',
  path: '/projects/$projectId/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$projectId/folders/$folderId.lazy').then((d) => d.Route),
)
const ProjectsProjectIdFilesFileIdRoute = ProjectsProjectIdFilesFileIdRouteImport.update({
  id: '/projects/$projectId/files/$fileId',
  path: '/projects/$projectId/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects/$projectId/files/$fileId.lazy').then((d) => d.Route))
const ProjectsProjectIdCollectionsCollectionIdRoute =
  ProjectsProjectIdCollectionsCollectionIdRouteImport.update({
    id: '/projects/$projectId/collections/$collectionId',
    path: '/projects/$projectId/collections/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/projects/$projectId/collections/$collectionId.lazy').then((d) => d.Route),
  )
const ProjectsProjectIdFoldersFolderIdAgentsmdRoute =
  ProjectsProjectIdFoldersFolderIdAgentsmdRouteImport.update({
    id: '/projects/$projectId/folders/$folderId_/agentsmd',
    path: '/projects/$projectId/folders/$folderId/agentsmd',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/projects/$projectId/folders/$folderId_.agentsmd.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/projects/$projectId/agentsmd': typeof ProjectsProjectIdAgentsmdRoute
  '/projects/$projectId/recently-deleted': typeof ProjectsProjectIdRecentlyDeletedRoute
  '/teams/$teamId/dashboard': typeof TeamsTeamIdDashboardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/share/$shareId/': typeof ShareShareIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/collections/$collectionId': typeof ProjectsProjectIdCollectionsCollectionIdRoute
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/projects/$projectId/folders/$folderId': typeof ProjectsProjectIdFoldersFolderIdRoute
  '/projects/$projectId/shares/$shareId': typeof ProjectsProjectIdSharesShareIdRoute
  '/share/$shareId/files/$fileId': typeof ShareShareIdFilesFileIdRoute
  '/share/$shareId/folders/$folderId': typeof ShareShareIdFoldersFolderIdRoute
  '/projects/$projectId/collections/': typeof ProjectsProjectIdCollectionsIndexRoute
  '/projects/$projectId/shares/': typeof ProjectsProjectIdSharesIndexRoute
  '/projects/$projectId/folders/$folderId/agentsmd': typeof ProjectsProjectIdFoldersFolderIdAgentsmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId/agentsmd': typeof ProjectsProjectIdAgentsmdRoute
  '/projects/$projectId/recently-deleted': typeof ProjectsProjectIdRecentlyDeletedRoute
  '/teams/$teamId/dashboard': typeof TeamsTeamIdDashboardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/share/$shareId': typeof ShareShareIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/collections/$collectionId': typeof ProjectsProjectIdCollectionsCollectionIdRoute
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/projects/$projectId/folders/$folderId': typeof ProjectsProjectIdFoldersFolderIdRoute
  '/projects/$projectId/shares/$shareId': typeof ProjectsProjectIdSharesShareIdRoute
  '/share/$shareId/files/$fileId': typeof ShareShareIdFilesFileIdRoute
  '/share/$shareId/folders/$folderId': typeof ShareShareIdFoldersFolderIdRoute
  '/projects/$projectId/collections': typeof ProjectsProjectIdCollectionsIndexRoute
  '/projects/$projectId/shares': typeof ProjectsProjectIdSharesIndexRoute
  '/projects/$projectId/folders/$folderId/agentsmd': typeof ProjectsProjectIdFoldersFolderIdAgentsmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/share/$shareId': typeof ShareShareIdRouteWithChildren
  '/projects/$projectId/agentsmd': typeof ProjectsProjectIdAgentsmdRoute
  '/projects/$projectId/recently-deleted': typeof ProjectsProjectIdRecentlyDeletedRoute
  '/teams/$teamId/dashboard': typeof TeamsTeamIdDashboardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/share/$shareId/': typeof ShareShareIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/collections/$collectionId': typeof ProjectsProjectIdCollectionsCollectionIdRoute
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/projects/$projectId/folders/$folderId': typeof ProjectsProjectIdFoldersFolderIdRoute
  '/projects/$projectId/shares/$shareId': typeof ProjectsProjectIdSharesShareIdRoute
  '/share/$shareId/files/$fileId': typeof ShareShareIdFilesFileIdRoute
  '/share/$shareId/folders/$folderId': typeof ShareShareIdFoldersFolderIdRoute
  '/projects/$projectId/collections/': typeof ProjectsProjectIdCollectionsIndexRoute
  '/projects/$projectId/shares/': typeof ProjectsProjectIdSharesIndexRoute
  '/projects/$projectId/folders/$folderId_/agentsmd': typeof ProjectsProjectIdFoldersFolderIdAgentsmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/share/$shareId'
    | '/projects/$projectId/agentsmd'
    | '/projects/$projectId/recently-deleted'
    | '/teams/$teamId/dashboard'
    | '/teams/$teamId/settings'
    | '/projects/$projectId/'
    | '/share/$shareId/'
    | '/teams/$teamId/'
    | '/projects/$projectId/collections/$collectionId'
    | '/projects/$projectId/files/$fileId'
    | '/projects/$projectId/folders/$folderId'
    | '/projects/$projectId/shares/$shareId'
    | '/share/$shareId/files/$fileId'
    | '/share/$shareId/folders/$folderId'
    | '/projects/$projectId/collections/'
    | '/projects/$projectId/shares/'
    | '/projects/$projectId/folders/$folderId/agentsmd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId/agentsmd'
    | '/projects/$projectId/recently-deleted'
    | '/teams/$teamId/dashboard'
    | '/teams/$teamId/settings'
    | '/projects/$projectId'
    | '/share/$shareId'
    | '/teams/$teamId'
    | '/projects/$projectId/collections/$collectionId'
    | '/projects/$projectId/files/$fileId'
    | '/projects/$projectId/folders/$folderId'
    | '/projects/$projectId/shares/$shareId'
    | '/share/$shareId/files/$fileId'
    | '/share/$shareId/folders/$folderId'
    | '/projects/$projectId/collections'
    | '/projects/$projectId/shares'
    | '/projects/$projectId/folders/$folderId/agentsmd'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/share/$shareId'
    | '/projects/$projectId/agentsmd'
    | '/projects/$projectId/recently-deleted'
    | '/teams/$teamId/dashboard'
    | '/teams/$teamId/settings'
    | '/projects/$projectId/'
    | '/share/$shareId/'
    | '/teams/$teamId/'
    | '/projects/$projectId/collections/$collectionId'
    | '/projects/$projectId/files/$fileId'
    | '/projects/$projectId/folders/$folderId'
    | '/projects/$projectId/shares/$shareId'
    | '/share/$shareId/files/$fileId'
    | '/share/$shareId/folders/$folderId'
    | '/projects/$projectId/collections/'
    | '/projects/$projectId/shares/'
    | '/projects/$projectId/folders/$folderId_/agentsmd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ShareShareIdRoute: typeof ShareShareIdRouteWithChildren
  ProjectsProjectIdAgentsmdRoute: typeof ProjectsProjectIdAgentsmdRoute
  ProjectsProjectIdRecentlyDeletedRoute: typeof ProjectsProjectIdRecentlyDeletedRoute
  TeamsTeamIdDashboardRoute: typeof TeamsTeamIdDashboardRoute
  TeamsTeamIdSettingsRoute: typeof TeamsTeamIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  ProjectsProjectIdCollectionsCollectionIdRoute: typeof ProjectsProjectIdCollectionsCollectionIdRoute
  ProjectsProjectIdFilesFileIdRoute: typeof ProjectsProjectIdFilesFileIdRoute
  ProjectsProjectIdFoldersFolderIdRoute: typeof ProjectsProjectIdFoldersFolderIdRoute
  ProjectsProjectIdSharesShareIdRoute: typeof ProjectsProjectIdSharesShareIdRoute
  ProjectsProjectIdCollectionsIndexRoute: typeof ProjectsProjectIdCollectionsIndexRoute
  ProjectsProjectIdSharesIndexRoute: typeof ProjectsProjectIdSharesIndexRoute
  ProjectsProjectIdFoldersFolderIdAgentsmdRoute: typeof ProjectsProjectIdFoldersFolderIdAgentsmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId/': {
      id: '/share/$shareId/'
      path: '/'
      fullPath: '/share/$shareId/'
      preLoaderRoute: typeof ShareShareIdIndexRouteImport
      parentRoute: typeof ShareShareIdRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/settings': {
      id: '/teams/$teamId/settings'
      path: '/teams/$teamId/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/dashboard': {
      id: '/teams/$teamId/dashboard'
      path: '/teams/$teamId/dashboard'
      fullPath: '/teams/$teamId/dashboard'
      preLoaderRoute: typeof TeamsTeamIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/recently-deleted': {
      id: '/projects/$projectId/recently-deleted'
      path: '/projects/$projectId/recently-deleted'
      fullPath: '/projects/$projectId/recently-deleted'
      preLoaderRoute: typeof ProjectsProjectIdRecentlyDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/agentsmd': {
      id: '/projects/$projectId/agentsmd'
      path: '/projects/$projectId/agentsmd'
      fullPath: '/projects/$projectId/agentsmd'
      preLoaderRoute: typeof ProjectsProjectIdAgentsmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/shares/': {
      id: '/projects/$projectId/shares/'
      path: '/projects/$projectId/shares'
      fullPath: '/projects/$projectId/shares/'
      preLoaderRoute: typeof ProjectsProjectIdSharesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/collections/': {
      id: '/projects/$projectId/collections/'
      path: '/projects/$projectId/collections'
      fullPath: '/projects/$projectId/collections/'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId/folders/$folderId': {
      id: '/share/$shareId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/share/$shareId/folders/$folderId'
      preLoaderRoute: typeof ShareShareIdFoldersFolderIdRouteImport
      parentRoute: typeof ShareShareIdRoute
    }
    '/share/$shareId/files/$fileId': {
      id: '/share/$shareId/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/share/$shareId/files/$fileId'
      preLoaderRoute: typeof ShareShareIdFilesFileIdRouteImport
      parentRoute: typeof ShareShareIdRoute
    }
    '/projects/$projectId/shares/$shareId': {
      id: '/projects/$projectId/shares/$shareId'
      path: '/projects/$projectId/shares/$shareId'
      fullPath: '/projects/$projectId/shares/$shareId'
      preLoaderRoute: typeof ProjectsProjectIdSharesShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/folders/$folderId': {
      id: '/projects/$projectId/folders/$folderId'
      path: '/projects/$projectId/folders/$folderId'
      fullPath: '/projects/$projectId/folders/$folderId'
      preLoaderRoute: typeof ProjectsProjectIdFoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/files/$fileId': {
      id: '/projects/$projectId/files/$fileId'
      path: '/projects/$projectId/files/$fileId'
      fullPath: '/projects/$projectId/files/$fileId'
      preLoaderRoute: typeof ProjectsProjectIdFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/collections/$collectionId': {
      id: '/projects/$projectId/collections/$collectionId'
      path: '/projects/$projectId/collections/$collectionId'
      fullPath: '/projects/$projectId/collections/$collectionId'
      preLoaderRoute: typeof ProjectsProjectIdCollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/folders/$folderId_/agentsmd': {
      id: '/projects/$projectId/folders/$folderId_/agentsmd'
      path: '/projects/$projectId/folders/$folderId/agentsmd'
      fullPath: '/projects/$projectId/folders/$folderId/agentsmd'
      preLoaderRoute: typeof ProjectsProjectIdFoldersFolderIdAgentsmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShareShareIdRouteChildren {
  ShareShareIdIndexRoute: typeof ShareShareIdIndexRoute
  ShareShareIdFilesFileIdRoute: typeof ShareShareIdFilesFileIdRoute
  ShareShareIdFoldersFolderIdRoute: typeof ShareShareIdFoldersFolderIdRoute
}

const ShareShareIdRouteChildren: ShareShareIdRouteChildren = {
  ShareShareIdIndexRoute: ShareShareIdIndexRoute,
  ShareShareIdFilesFileIdRoute: ShareShareIdFilesFileIdRoute,
  ShareShareIdFoldersFolderIdRoute: ShareShareIdFoldersFolderIdRoute,
}

const ShareShareIdRouteWithChildren = ShareShareIdRoute._addFileChildren(ShareShareIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ShareShareIdRoute: ShareShareIdRouteWithChildren,
  ProjectsProjectIdAgentsmdRoute: ProjectsProjectIdAgentsmdRoute,
  ProjectsProjectIdRecentlyDeletedRoute: ProjectsProjectIdRecentlyDeletedRoute,
  TeamsTeamIdDashboardRoute: TeamsTeamIdDashboardRoute,
  TeamsTeamIdSettingsRoute: TeamsTeamIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  ProjectsProjectIdCollectionsCollectionIdRoute: ProjectsProjectIdCollectionsCollectionIdRoute,
  ProjectsProjectIdFilesFileIdRoute: ProjectsProjectIdFilesFileIdRoute,
  ProjectsProjectIdFoldersFolderIdRoute: ProjectsProjectIdFoldersFolderIdRoute,
  ProjectsProjectIdSharesShareIdRoute: ProjectsProjectIdSharesShareIdRoute,
  ProjectsProjectIdCollectionsIndexRoute: ProjectsProjectIdCollectionsIndexRoute,
  ProjectsProjectIdSharesIndexRoute: ProjectsProjectIdSharesIndexRoute,
  ProjectsProjectIdFoldersFolderIdAgentsmdRoute: ProjectsProjectIdFoldersFolderIdAgentsmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
